### ISSUE TITLE
Socket IO errors should result in Kontena::Websocket::SocketError

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena-websocket-client#1]
The socket read/write/connect calls do not trap all of the resulting IO errors, which should be re-raised as `Kontena::Websocket::SocketError`s for handling.

**Comment by SpComb** [comment]
```
I, [2017-07-19T13:24:06.356243 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://192.168.66.1:9293
E, [2017-07-19T13:24:06.440852 #1] ERROR -- Kontena::WebsocketClient: Connection reset by peer (Errno::ECONNRESET)
/usr/lib/ruby/2.3.0/openssl/buffering.rb:379:in `syswrite_nonblock'
/usr/lib/ruby/2.3.0/openssl/buffering.rb:379:in `write_nonblock'
/usr/lib/ruby/gems/2.3.0/bundler/gems/kontena-websocket-client-e70d1435cdce/lib/kontena/websocket/client/connection.rb:56:in `block in write'
/usr/lib/ruby/gems/2.3.0/bundler/gems/kontena-websocket-client-e70d1435cdce/lib/kontena/websocket/client/connection.rb:26:in `nonblocking_timeout'
/usr/lib/ruby/gems/2.3.0/bundler/gems/kontena-websocket-client-e70d1435cdce/lib/kontena/websocket/client/connection.rb:55:in `write'
/usr/lib/ruby/gems/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/client.rb:56:in `start'
/usr/lib/ruby/gems/2.3.0/bundler/gems/kontena-websocket-client-e70d1435cdce/lib/kontena/websocket/client.rb:621:in `websocket_open'
/usr/lib/ruby/gems/2.3.0/bundler/gems/kontena-websocket-client-e70d1435cdce/lib/kontena/websocket/client.rb:227:in `connect'
/app/lib/kontena/websocket_client.rb:135:in `block in connect_client'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
(celluloid):0:in `remote procedure call'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:142:in `value'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:96:in `value'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:446:in `defer'
/app/lib/kontena/websocket_client.rb:129:in `connect_client'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```
